#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-spatial4j
Version  : 0.4.1
Release  : 1
URL      : https://github.com/locationtech/spatial4j/archive/spatial4j-0.4.1.tar.gz
Source0  : https://github.com/locationtech/spatial4j/archive/spatial4j-0.4.1.tar.gz
Source1  : https://repo.maven.apache.org/maven2/com/spatial4j/spatial4j/0.4.1/spatial4j-0.4.1.jar
Source2  : https://repo.maven.apache.org/maven2/com/spatial4j/spatial4j/0.4.1/spatial4j-0.4.1.pom
Source3  : https://repo.maven.apache.org/maven2/com/spatial4j/spatial4j/0.5/spatial4j-0.5.jar
Source4  : https://repo.maven.apache.org/maven2/com/spatial4j/spatial4j/0.5/spatial4j-0.5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-spatial4j-data = %{version}-%{release}
Requires: mvn-spatial4j-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
# Spatial4j
Spatial4j is a general purpose spatial / geospatial [ASL](http://www.apache.org/licenses/LICENSE-2.0.html) licensed open-source Java library. It's core capabilities are 3-fold: to provide common shapes that can work in Euclidean and geodesic (surface of sphere) world models, to provide distance calculations and other math, and to read shapes from [WKT](http://en.wikipedia.org/wiki/Well-known_text) formatted strings.  Spatial4j is a [pending](http://www.locationtech.org/proposals/spatial4j) member of the [LocationTech](http://www.locationtech.org) Industry Working Group family of projects.

%package data
Summary: data components for the mvn-spatial4j package.
Group: Data

%description data
data components for the mvn-spatial4j package.


%package license
Summary: license components for the mvn-spatial4j package.
Group: Default

%description license
license components for the mvn-spatial4j package.


%prep
%setup -q -n spatial4j-spatial4j-0.4.1

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-spatial4j
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-spatial4j/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.4.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.4.1/spatial4j-0.4.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.4.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.4.1/spatial4j-0.4.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.5
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.5/spatial4j-0.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.5
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.5/spatial4j-0.5.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.4.1/spatial4j-0.4.1.jar
/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.4.1/spatial4j-0.4.1.pom
/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.5/spatial4j-0.5.jar
/usr/share/java/.m2/repository/com/spatial4j/spatial4j/0.5/spatial4j-0.5.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-spatial4j/LICENSE.txt
